# SPDX-License-Identifier: BSD-2-Clause
sudo: required
language: c
services:
- docker
compiler:
- gcc
env:
  global:
    - PYTHON_INTERPRETER=python3.7
  matrix:
    - DOCKER_TAG=ubuntu-16.04
    - DOCKER_TAG=ubuntu-18.04
script:
  - ./.ci/travis.run
after_failure:
  - cat build/test-suite.log
